---
kind: pipeline
type: kubernetes
name: build

trigger:
  event: [ push ]
  branch: [ master ]

steps:
- name: build
  image: plugins/docker
  settings:
    registry: docker.jbrumond.me
    username: drone
    password:
      from_secret: docker-jbrumond-me-password
    repo: docker.jbrumond.me/minimal-blog
    dry_run: true

---
kind: pipeline
type: kubernetes
name: publish-image

trigger:
  event: [ promote ]
  target: [ publish ]

steps:
- name: setup
  image: node:16-alpine
  commands:
  - node ./scripts/publish-setup.js

- name: build-and-publish
  image: plugins/docker
  settings:
    registry: docker.jbrumond.me
    username: drone
    password:
      from_secret: docker-jbrumond-me-password
    repo: docker.jbrumond.me/minimal-blog
