---
kind: pipeline
type: kubernetes
name: build

trigger:
  event: [ push ]
  branch: [ master ]

steps:
# - name: node16
#   image: node:16-alpine
#   commands:
#   - apk add --no-cache python3 g++ make
#   - npm install
#   - npm run build
- name: build
  image: plugins/docker
  settings:
    registry: https://docker.jbrumond.me
    username: drone
    password:
      from_secret: docker-jbrumond-me-password
    repo: docker.jbrumond.me/minimal-blog
    dry_run: true

---
kind: pipeline
type: kubernetes
name: deploy-stg

trigger:
  event: [ promote ]
  target: [ publish ]

steps:
- name: build-and-publish
  image: plugins/docker
  settings:
    registry: https://docker.jbrumond.me
    username: drone
    password:
      from_secret: docker-jbrumond-me-password
    repo: docker.jbrumond.me/minimal-blog
    tags:
    - latest
    - 0.1-alpha
