# see: https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md

name: Build Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Setup publish tags
      id: setup_tags
      run: |
        node scripts/publish-setup.js jbrumond/minimal-blog
        echo "TAGS_TO_PUBLISH=$( cat .tags )" >> $GITHUB_ENV
    - name: Build Docker images
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: false
        tags: ${{ env.TAGS_TO_PUBLISH }}
        # tags: jbrumond/minimal-blog:latest
